#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3082
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuTai.Component
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="FuTai")]
	public partial class FuTaiDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public FuTaiDataContext() : 
				base(global::FuTai.Component.Properties.Settings.Default.FuTaiConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public FuTaiDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FuTaiDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FuTaiDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FuTaiDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<Diamond> Diamonds
		{
			get
			{
				return this.GetTable<Diamond>();
			}
		}
		
		public System.Data.Linq.Table<DiamondGroup> DiamondGroups
		{
			get
			{
				return this.GetTable<DiamondGroup>();
			}
		}
		
		public System.Data.Linq.Table<DiamondOrnament> DiamondOrnaments
		{
			get
			{
				return this.GetTable<DiamondOrnament>();
			}
		}
		
		public System.Data.Linq.Table<DiamondRing> DiamondRings
		{
			get
			{
				return this.GetTable<DiamondRing>();
			}
		}
		
		public System.Data.Linq.Table<GoldOrnament> GoldOrnaments
		{
			get
			{
				return this.GetTable<GoldOrnament>();
			}
		}
		
		public System.Data.Linq.Table<Jewel> Jewels
		{
			get
			{
				return this.GetTable<Jewel>();
			}
		}
		
		public System.Data.Linq.Table<PairRing> PairRings
		{
			get
			{
				return this.GetTable<PairRing>();
			}
		}
		
		public System.Data.Linq.Table<RingBracket> RingBrackets
		{
			get
			{
				return this.GetTable<RingBracket>();
			}
		}
		
		public System.Data.Linq.Table<_RingBracket> _RingBrackets
		{
			get
			{
				return this.GetTable<_RingBracket>();
			}
		}
		
		[Function(Name="dbo.search_SearchRingBracket")]
		public ISingleResult<search_SearchRingBracket_个结果> SearchRingBracket([Parameter(Name="Price1", DbType="Decimal")] System.Nullable<decimal> price1, [Parameter(Name="Price2", DbType="Decimal")] System.Nullable<decimal> price2, [Parameter(Name="Type1", DbType="Int")] System.Nullable<int> type1, [Parameter(Name="Type2", DbType="Int")] System.Nullable<int> type2)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), price1, price2, type1, type2);
			return ((ISingleResult<search_SearchRingBracket_个结果>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.search_SearchDiamond")]
		public ISingleResult<search_SearchDiamond_个结果> SearchDiamond([Parameter(Name="Price1", DbType="Decimal")] System.Nullable<decimal> price1, [Parameter(Name="Price2", DbType="Decimal")] System.Nullable<decimal> price2, [Parameter(Name="Type1", DbType="Int")] System.Nullable<int> type1, [Parameter(Name="Type2", DbType="Int")] System.Nullable<int> type2)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), price1, price2, type1, type2);
			return ((ISingleResult<search_SearchDiamond_个结果>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.search_SearchDiamondOrnament")]
		public ISingleResult<search_SearchDiamondOrnament_个结果> SearchDiamondOrnament([Parameter(Name="Price1", DbType="Decimal")] System.Nullable<decimal> price1, [Parameter(Name="Price2", DbType="Decimal")] System.Nullable<decimal> price2, [Parameter(Name="Type1", DbType="Int")] System.Nullable<int> type1, [Parameter(Name="Type2", DbType="Int")] System.Nullable<int> type2)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), price1, price2, type1, type2);
			return ((ISingleResult<search_SearchDiamondOrnament_个结果>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.search_SearchJewel")]
		public ISingleResult<search_SearchJewel_个结果> SearchJewel([Parameter(Name="Price1", DbType="Decimal")] System.Nullable<decimal> price1, [Parameter(Name="Price2", DbType="Decimal")] System.Nullable<decimal> price2, [Parameter(Name="Type1", DbType="Int")] System.Nullable<int> type1, [Parameter(Name="Type2", DbType="Int")] System.Nullable<int> type2)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), price1, price2, type1, type2);
			return ((ISingleResult<search_SearchJewel_个结果>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.search_SearchPairRing")]
		public ISingleResult<search_SearchPairRing_个结果> SearchPairRing([Parameter(Name="Price1", DbType="Decimal")] System.Nullable<decimal> price1, [Parameter(Name="Price2", DbType="Decimal")] System.Nullable<decimal> price2, [Parameter(Name="Type1", DbType="Int")] System.Nullable<int> type1, [Parameter(Name="Type2", DbType="Int")] System.Nullable<int> type2)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), price1, price2, type1, type2);
			return ((ISingleResult<search_SearchPairRing_个结果>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.search_SearchDiamondRing")]
		public ISingleResult<search_SearchDiamondRing_个结果> SearchDiamondRing([Parameter(Name="Price1", DbType="Decimal")] System.Nullable<decimal> price1, [Parameter(Name="Price2", DbType="Decimal")] System.Nullable<decimal> price2, [Parameter(Name="Type1", DbType="Int")] System.Nullable<int> type1, [Parameter(Name="Type2", DbType="Int")] System.Nullable<int> type2)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), price1, price2, type1, type2);
			return ((ISingleResult<search_SearchDiamondRing_个结果>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.search_SearchGoldOrnament")]
		public ISingleResult<search_SearchGoldOrnament_个结果> SearchGoldOrnament([Parameter(Name="Price1", DbType="Decimal")] System.Nullable<decimal> price1, [Parameter(Name="Price2", DbType="Decimal")] System.Nullable<decimal> price2, [Parameter(Name="Type1", DbType="Int")] System.Nullable<int> type1, [Parameter(Name="Type2", DbType="Int")] System.Nullable<int> type2)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), price1, price2, type1, type2);
			return ((ISingleResult<search_SearchGoldOrnament_个结果>)(result.ReturnValue));
		}
	}
	
	[Table(Name="dbo.[User]")]
	public partial class User
	{
		
		private System.Nullable<int> _UserId;
		
		private string _CardId;
		
		private string _Email;
		
		private string _NickName;
		
		private string _Password;
		
		private System.Nullable<int> _Authority;
		
		private string _UserName;
		
		private System.Nullable<bool> _Sex;
		
		private string _Phone;
		
		private string _Impression;
		
		public User()
		{
		}
		
		[Column(Storage="_UserId", DbType="Int")]
		public System.Nullable<int> UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[Column(Storage="_CardId", DbType="VarChar(20)")]
		public string CardId
		{
			get
			{
				return this._CardId;
			}
			set
			{
				if ((this._CardId != value))
				{
					this._CardId = value;
				}
			}
		}
		
		[Column(Storage="_Email", DbType="VarChar(20)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[Column(Storage="_NickName", DbType="NVarChar(20)")]
		public string NickName
		{
			get
			{
				return this._NickName;
			}
			set
			{
				if ((this._NickName != value))
				{
					this._NickName = value;
				}
			}
		}
		
		[Column(Storage="_Password", DbType="VarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[Column(Storage="_Authority", DbType="Int")]
		public System.Nullable<int> Authority
		{
			get
			{
				return this._Authority;
			}
			set
			{
				if ((this._Authority != value))
				{
					this._Authority = value;
				}
			}
		}
		
		[Column(Storage="_UserName", DbType="NVarChar(20)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[Column(Storage="_Sex", DbType="Bit")]
		public System.Nullable<bool> Sex
		{
			get
			{
				return this._Sex;
			}
			set
			{
				if ((this._Sex != value))
				{
					this._Sex = value;
				}
			}
		}
		
		[Column(Storage="_Phone", DbType="NChar(10)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this._Phone = value;
				}
			}
		}
		
		[Column(Storage="_Impression", DbType="NVarChar(200)")]
		public string Impression
		{
			get
			{
				return this._Impression;
			}
			set
			{
				if ((this._Impression != value))
				{
					this._Impression = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.Diamond")]
	public partial class Diamond
	{
		
		private string _ProductID;
		
		private string _StockNumber;
		
		private string _Carat;
		
		private string _Clarity;
		
		private string _Color;
		
		private string _Cut;
		
		private System.Nullable<decimal> _Price;
		
		public Diamond()
		{
		}
		
		[Column(Storage="_ProductID", DbType="Char(10)")]
		public string ProductID
		{
			get
			{
				return this._ProductID;
			}
			set
			{
				if ((this._ProductID != value))
				{
					this._ProductID = value;
				}
			}
		}
		
		[Column(Storage="_StockNumber", DbType="VarChar(20)")]
		public string StockNumber
		{
			get
			{
				return this._StockNumber;
			}
			set
			{
				if ((this._StockNumber != value))
				{
					this._StockNumber = value;
				}
			}
		}
		
		[Column(Storage="_Carat", DbType="NChar(10)")]
		public string Carat
		{
			get
			{
				return this._Carat;
			}
			set
			{
				if ((this._Carat != value))
				{
					this._Carat = value;
				}
			}
		}
		
		[Column(Storage="_Clarity", DbType="VarChar(10)")]
		public string Clarity
		{
			get
			{
				return this._Clarity;
			}
			set
			{
				if ((this._Clarity != value))
				{
					this._Clarity = value;
				}
			}
		}
		
		[Column(Storage="_Color", DbType="VarChar(10)")]
		public string Color
		{
			get
			{
				return this._Color;
			}
			set
			{
				if ((this._Color != value))
				{
					this._Color = value;
				}
			}
		}
		
		[Column(Storage="_Cut", DbType="VarChar(10)")]
		public string Cut
		{
			get
			{
				return this._Cut;
			}
			set
			{
				if ((this._Cut != value))
				{
					this._Cut = value;
				}
			}
		}
		
		[Column(Storage="_Price", DbType="Money")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.DiamondGroup")]
	public partial class DiamondGroup
	{
		
		private System.Nullable<int> _DiamondGroupId;
		
		private System.Nullable<int> _UserId;
		
		private System.Nullable<int> _DiamondId;
		
		private string _MetalType;
		
		private string _Style;
		
		private System.Nullable<int> _RingBracketId;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<System.DateTime> _UpdateDate;
		
		private System.Nullable<System.DateTime> _DeleteDate;
		
		public DiamondGroup()
		{
		}
		
		[Column(Storage="_DiamondGroupId", DbType="Int")]
		public System.Nullable<int> DiamondGroupId
		{
			get
			{
				return this._DiamondGroupId;
			}
			set
			{
				if ((this._DiamondGroupId != value))
				{
					this._DiamondGroupId = value;
				}
			}
		}
		
		[Column(Storage="_UserId", DbType="Int")]
		public System.Nullable<int> UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[Column(Storage="_DiamondId", DbType="Int")]
		public System.Nullable<int> DiamondId
		{
			get
			{
				return this._DiamondId;
			}
			set
			{
				if ((this._DiamondId != value))
				{
					this._DiamondId = value;
				}
			}
		}
		
		[Column(Storage="_MetalType", DbType="VarChar(20)")]
		public string MetalType
		{
			get
			{
				return this._MetalType;
			}
			set
			{
				if ((this._MetalType != value))
				{
					this._MetalType = value;
				}
			}
		}
		
		[Column(Storage="_Style", DbType="VarChar(20)")]
		public string Style
		{
			get
			{
				return this._Style;
			}
			set
			{
				if ((this._Style != value))
				{
					this._Style = value;
				}
			}
		}
		
		[Column(Storage="_RingBracketId", DbType="Int")]
		public System.Nullable<int> RingBracketId
		{
			get
			{
				return this._RingBracketId;
			}
			set
			{
				if ((this._RingBracketId != value))
				{
					this._RingBracketId = value;
				}
			}
		}
		
		[Column(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[Column(Storage="_UpdateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this._UpdateDate = value;
				}
			}
		}
		
		[Column(Storage="_DeleteDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeleteDate
		{
			get
			{
				return this._DeleteDate;
			}
			set
			{
				if ((this._DeleteDate != value))
				{
					this._DeleteDate = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.DiamondOrnament")]
	public partial class DiamondOrnament
	{
		
		private System.Nullable<int> _DiamondOrnamentId;
		
		private string _OrnamentType;
		
		public DiamondOrnament()
		{
		}
		
		[Column(Storage="_DiamondOrnamentId", DbType="Int")]
		public System.Nullable<int> DiamondOrnamentId
		{
			get
			{
				return this._DiamondOrnamentId;
			}
			set
			{
				if ((this._DiamondOrnamentId != value))
				{
					this._DiamondOrnamentId = value;
				}
			}
		}
		
		[Column(Storage="_OrnamentType", DbType="NChar(10)")]
		public string OrnamentType
		{
			get
			{
				return this._OrnamentType;
			}
			set
			{
				if ((this._OrnamentType != value))
				{
					this._OrnamentType = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.DiamondRing")]
	public partial class DiamondRing
	{
		
		private System.Nullable<int> _DiamondRingId;
		
		private string _StockNumber;
		
		private string _Type;
		
		public DiamondRing()
		{
		}
		
		[Column(Storage="_DiamondRingId", DbType="Int")]
		public System.Nullable<int> DiamondRingId
		{
			get
			{
				return this._DiamondRingId;
			}
			set
			{
				if ((this._DiamondRingId != value))
				{
					this._DiamondRingId = value;
				}
			}
		}
		
		[Column(Storage="_StockNumber", DbType="VarChar(20)")]
		public string StockNumber
		{
			get
			{
				return this._StockNumber;
			}
			set
			{
				if ((this._StockNumber != value))
				{
					this._StockNumber = value;
				}
			}
		}
		
		[Column(Storage="_Type", DbType="NChar(10)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.GoldOrnament")]
	public partial class GoldOrnament
	{
		
		private System.Nullable<int> _GoldOrnamentId;
		
		private string _OrnamentType;
		
		public GoldOrnament()
		{
		}
		
		[Column(Storage="_GoldOrnamentId", DbType="Int")]
		public System.Nullable<int> GoldOrnamentId
		{
			get
			{
				return this._GoldOrnamentId;
			}
			set
			{
				if ((this._GoldOrnamentId != value))
				{
					this._GoldOrnamentId = value;
				}
			}
		}
		
		[Column(Storage="_OrnamentType", DbType="NChar(10)")]
		public string OrnamentType
		{
			get
			{
				return this._OrnamentType;
			}
			set
			{
				if ((this._OrnamentType != value))
				{
					this._OrnamentType = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.Jewel")]
	public partial class Jewel
	{
		
		private System.Nullable<int> _JewelId;
		
		private string _JewelType;
		
		public Jewel()
		{
		}
		
		[Column(Storage="_JewelId", DbType="Int")]
		public System.Nullable<int> JewelId
		{
			get
			{
				return this._JewelId;
			}
			set
			{
				if ((this._JewelId != value))
				{
					this._JewelId = value;
				}
			}
		}
		
		[Column(Storage="_JewelType", DbType="NChar(10)")]
		public string JewelType
		{
			get
			{
				return this._JewelType;
			}
			set
			{
				if ((this._JewelType != value))
				{
					this._JewelType = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.PairRing")]
	public partial class PairRing
	{
		
		private System.Nullable<int> _PairRingId;
		
		private string _StockNumber;
		
		private string _RingType;
		
		public PairRing()
		{
		}
		
		[Column(Storage="_PairRingId", DbType="Int")]
		public System.Nullable<int> PairRingId
		{
			get
			{
				return this._PairRingId;
			}
			set
			{
				if ((this._PairRingId != value))
				{
					this._PairRingId = value;
				}
			}
		}
		
		[Column(Storage="_StockNumber", DbType="NChar(10)")]
		public string StockNumber
		{
			get
			{
				return this._StockNumber;
			}
			set
			{
				if ((this._StockNumber != value))
				{
					this._StockNumber = value;
				}
			}
		}
		
		[Column(Storage="_RingType", DbType="NChar(10)")]
		public string RingType
		{
			get
			{
				return this._RingType;
			}
			set
			{
				if ((this._RingType != value))
				{
					this._RingType = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.RingBracket")]
	public partial class RingBracket
	{
		
		private System.Nullable<int> _BracketId;
		
		private string _MetalType;
		
		private string _Style;
		
		private System.Nullable<int> _StyleId;
		
		private string _Craft;
		
		public RingBracket()
		{
		}
		
		[Column(Storage="_BracketId", DbType="Int")]
		public System.Nullable<int> BracketId
		{
			get
			{
				return this._BracketId;
			}
			set
			{
				if ((this._BracketId != value))
				{
					this._BracketId = value;
				}
			}
		}
		
		[Column(Storage="_MetalType", DbType="VarChar(20)")]
		public string MetalType
		{
			get
			{
				return this._MetalType;
			}
			set
			{
				if ((this._MetalType != value))
				{
					this._MetalType = value;
				}
			}
		}
		
		[Column(Storage="_Style", DbType="VarChar(20)")]
		public string Style
		{
			get
			{
				return this._Style;
			}
			set
			{
				if ((this._Style != value))
				{
					this._Style = value;
				}
			}
		}
		
		[Column(Storage="_StyleId", DbType="Int")]
		public System.Nullable<int> StyleId
		{
			get
			{
				return this._StyleId;
			}
			set
			{
				if ((this._StyleId != value))
				{
					this._StyleId = value;
				}
			}
		}
		
		[Column(Storage="_Craft", DbType="VarChar(20)")]
		public string Craft
		{
			get
			{
				return this._Craft;
			}
			set
			{
				if ((this._Craft != value))
				{
					this._Craft = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.[\tRingBracket]")]
	public partial class _RingBracket
	{
		
		private System.Nullable<int> _RingBracketId;
		
		private string _MetalType;
		
		private string _Style;
		
		private System.Nullable<int> _StyleId;
		
		private string _Craft;
		
		public _RingBracket()
		{
		}
		
		[Column(Storage="_RingBracketId", DbType="Int")]
		public System.Nullable<int> RingBracketId
		{
			get
			{
				return this._RingBracketId;
			}
			set
			{
				if ((this._RingBracketId != value))
				{
					this._RingBracketId = value;
				}
			}
		}
		
		[Column(Storage="_MetalType", DbType="VarChar(20)")]
		public string MetalType
		{
			get
			{
				return this._MetalType;
			}
			set
			{
				if ((this._MetalType != value))
				{
					this._MetalType = value;
				}
			}
		}
		
		[Column(Storage="_Style", DbType="VarChar(20)")]
		public string Style
		{
			get
			{
				return this._Style;
			}
			set
			{
				if ((this._Style != value))
				{
					this._Style = value;
				}
			}
		}
		
		[Column(Storage="_StyleId", DbType="Int")]
		public System.Nullable<int> StyleId
		{
			get
			{
				return this._StyleId;
			}
			set
			{
				if ((this._StyleId != value))
				{
					this._StyleId = value;
				}
			}
		}
		
		[Column(Storage="_Craft", DbType="VarChar(20)")]
		public string Craft
		{
			get
			{
				return this._Craft;
			}
			set
			{
				if ((this._Craft != value))
				{
					this._Craft = value;
				}
			}
		}
	}
	
	public partial class search_SearchRingBracket_个结果
	{
		
		private int _BracketId;
		
		private string _MetalType;
		
		private string _Style;
		
		private System.Nullable<int> _StyleId;
		
		private System.Nullable<int> _Type1;
		
		private System.Nullable<int> _Type2;
		
		private string _Craft;
		
		private int _ProductId;
		
		private string _ProductType;
		
		private System.Nullable<decimal> _Price;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		public search_SearchRingBracket_个结果()
		{
		}
		
		[Column(Storage="_BracketId", DbType="Int NOT NULL")]
		public int BracketId
		{
			get
			{
				return this._BracketId;
			}
			set
			{
				if ((this._BracketId != value))
				{
					this._BracketId = value;
				}
			}
		}
		
		[Column(Storage="_MetalType", DbType="VarChar(20)")]
		public string MetalType
		{
			get
			{
				return this._MetalType;
			}
			set
			{
				if ((this._MetalType != value))
				{
					this._MetalType = value;
				}
			}
		}
		
		[Column(Storage="_Style", DbType="VarChar(20)")]
		public string Style
		{
			get
			{
				return this._Style;
			}
			set
			{
				if ((this._Style != value))
				{
					this._Style = value;
				}
			}
		}
		
		[Column(Storage="_StyleId", DbType="Int")]
		public System.Nullable<int> StyleId
		{
			get
			{
				return this._StyleId;
			}
			set
			{
				if ((this._StyleId != value))
				{
					this._StyleId = value;
				}
			}
		}
		
		[Column(Storage="_Type1", DbType="Int")]
		public System.Nullable<int> Type1
		{
			get
			{
				return this._Type1;
			}
			set
			{
				if ((this._Type1 != value))
				{
					this._Type1 = value;
				}
			}
		}
		
		[Column(Storage="_Type2", DbType="Int")]
		public System.Nullable<int> Type2
		{
			get
			{
				return this._Type2;
			}
			set
			{
				if ((this._Type2 != value))
				{
					this._Type2 = value;
				}
			}
		}
		
		[Column(Storage="_Craft", DbType="VarChar(20)")]
		public string Craft
		{
			get
			{
				return this._Craft;
			}
			set
			{
				if ((this._Craft != value))
				{
					this._Craft = value;
				}
			}
		}
		
		[Column(Storage="_ProductId", DbType="Int NOT NULL")]
		public int ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				if ((this._ProductId != value))
				{
					this._ProductId = value;
				}
			}
		}
		
		[Column(Storage="_ProductType", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ProductType
		{
			get
			{
				return this._ProductType;
			}
			set
			{
				if ((this._ProductType != value))
				{
					this._ProductType = value;
				}
			}
		}
		
		[Column(Storage="_Price", DbType="Decimal(0,0)")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[Column(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
	}
	
	public partial class search_SearchDiamond_个结果
	{
		
		private int _DiamondID;
		
		private string _StockNumber;
		
		private string _Carat;
		
		private string _Clarity;
		
		private string _Color;
		
		private string _Cut;
		
		private int _ProductId;
		
		private string _ProductType;
		
		private System.Nullable<decimal> _Price;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		public search_SearchDiamond_个结果()
		{
		}
		
		[Column(Storage="_DiamondID", DbType="Int NOT NULL")]
		public int DiamondID
		{
			get
			{
				return this._DiamondID;
			}
			set
			{
				if ((this._DiamondID != value))
				{
					this._DiamondID = value;
				}
			}
		}
		
		[Column(Storage="_StockNumber", DbType="VarChar(20)")]
		public string StockNumber
		{
			get
			{
				return this._StockNumber;
			}
			set
			{
				if ((this._StockNumber != value))
				{
					this._StockNumber = value;
				}
			}
		}
		
		[Column(Storage="_Carat", DbType="NChar(10)")]
		public string Carat
		{
			get
			{
				return this._Carat;
			}
			set
			{
				if ((this._Carat != value))
				{
					this._Carat = value;
				}
			}
		}
		
		[Column(Storage="_Clarity", DbType="VarChar(10)")]
		public string Clarity
		{
			get
			{
				return this._Clarity;
			}
			set
			{
				if ((this._Clarity != value))
				{
					this._Clarity = value;
				}
			}
		}
		
		[Column(Storage="_Color", DbType="VarChar(10)")]
		public string Color
		{
			get
			{
				return this._Color;
			}
			set
			{
				if ((this._Color != value))
				{
					this._Color = value;
				}
			}
		}
		
		[Column(Storage="_Cut", DbType="VarChar(10)")]
		public string Cut
		{
			get
			{
				return this._Cut;
			}
			set
			{
				if ((this._Cut != value))
				{
					this._Cut = value;
				}
			}
		}
		
		[Column(Storage="_ProductId", DbType="Int NOT NULL")]
		public int ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				if ((this._ProductId != value))
				{
					this._ProductId = value;
				}
			}
		}
		
		[Column(Storage="_ProductType", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ProductType
		{
			get
			{
				return this._ProductType;
			}
			set
			{
				if ((this._ProductType != value))
				{
					this._ProductType = value;
				}
			}
		}
		
		[Column(Storage="_Price", DbType="Money")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[Column(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
	}
	
	public partial class search_SearchDiamondOrnament_个结果
	{
		
		private int _DiamondOrnamentId;
		
		private string _OrnamentType;
		
		private System.Nullable<int> _Type1;
		
		private System.Nullable<int> _Type2;
		
		private int _ProductId;
		
		private string _ProductType;
		
		private System.Nullable<decimal> _Price;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		public search_SearchDiamondOrnament_个结果()
		{
		}
		
		[Column(Storage="_DiamondOrnamentId", DbType="Int NOT NULL")]
		public int DiamondOrnamentId
		{
			get
			{
				return this._DiamondOrnamentId;
			}
			set
			{
				if ((this._DiamondOrnamentId != value))
				{
					this._DiamondOrnamentId = value;
				}
			}
		}
		
		[Column(Storage="_OrnamentType", DbType="NChar(10)")]
		public string OrnamentType
		{
			get
			{
				return this._OrnamentType;
			}
			set
			{
				if ((this._OrnamentType != value))
				{
					this._OrnamentType = value;
				}
			}
		}
		
		[Column(Storage="_Type1", DbType="Int")]
		public System.Nullable<int> Type1
		{
			get
			{
				return this._Type1;
			}
			set
			{
				if ((this._Type1 != value))
				{
					this._Type1 = value;
				}
			}
		}
		
		[Column(Storage="_Type2", DbType="Int")]
		public System.Nullable<int> Type2
		{
			get
			{
				return this._Type2;
			}
			set
			{
				if ((this._Type2 != value))
				{
					this._Type2 = value;
				}
			}
		}
		
		[Column(Storage="_ProductId", DbType="Int NOT NULL")]
		public int ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				if ((this._ProductId != value))
				{
					this._ProductId = value;
				}
			}
		}
		
		[Column(Storage="_ProductType", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ProductType
		{
			get
			{
				return this._ProductType;
			}
			set
			{
				if ((this._ProductType != value))
				{
					this._ProductType = value;
				}
			}
		}
		
		[Column(Storage="_Price", DbType="Money")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[Column(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
	}
	
	public partial class search_SearchJewel_个结果
	{
		
		private int _PairRingId;
		
		private string _StockNumber;
		
		private string _RingType;
		
		private System.Nullable<int> _Type1;
		
		private int _ProductId;
		
		private string _ProductType;
		
		private System.Nullable<decimal> _Price;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		public search_SearchJewel_个结果()
		{
		}
		
		[Column(Storage="_PairRingId", DbType="Int NOT NULL")]
		public int PairRingId
		{
			get
			{
				return this._PairRingId;
			}
			set
			{
				if ((this._PairRingId != value))
				{
					this._PairRingId = value;
				}
			}
		}
		
		[Column(Storage="_StockNumber", DbType="NChar(10)")]
		public string StockNumber
		{
			get
			{
				return this._StockNumber;
			}
			set
			{
				if ((this._StockNumber != value))
				{
					this._StockNumber = value;
				}
			}
		}
		
		[Column(Storage="_RingType", DbType="NChar(10)")]
		public string RingType
		{
			get
			{
				return this._RingType;
			}
			set
			{
				if ((this._RingType != value))
				{
					this._RingType = value;
				}
			}
		}
		
		[Column(Storage="_Type1", DbType="Int")]
		public System.Nullable<int> Type1
		{
			get
			{
				return this._Type1;
			}
			set
			{
				if ((this._Type1 != value))
				{
					this._Type1 = value;
				}
			}
		}
		
		[Column(Storage="_ProductId", DbType="Int NOT NULL")]
		public int ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				if ((this._ProductId != value))
				{
					this._ProductId = value;
				}
			}
		}
		
		[Column(Storage="_ProductType", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ProductType
		{
			get
			{
				return this._ProductType;
			}
			set
			{
				if ((this._ProductType != value))
				{
					this._ProductType = value;
				}
			}
		}
		
		[Column(Storage="_Price", DbType="Money")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[Column(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
	}
	
	public partial class search_SearchPairRing_个结果
	{
		
		private int _GoldOrnamentId;
		
		private string _OrnamentType;
		
		private System.Nullable<int> _Type1;
		
		private System.Nullable<int> _Type2;
		
		private int _ProductId;
		
		private string _ProductType;
		
		private System.Nullable<decimal> _Price;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		public search_SearchPairRing_个结果()
		{
		}
		
		[Column(Storage="_GoldOrnamentId", DbType="Int NOT NULL")]
		public int GoldOrnamentId
		{
			get
			{
				return this._GoldOrnamentId;
			}
			set
			{
				if ((this._GoldOrnamentId != value))
				{
					this._GoldOrnamentId = value;
				}
			}
		}
		
		[Column(Storage="_OrnamentType", DbType="NChar(10)")]
		public string OrnamentType
		{
			get
			{
				return this._OrnamentType;
			}
			set
			{
				if ((this._OrnamentType != value))
				{
					this._OrnamentType = value;
				}
			}
		}
		
		[Column(Storage="_Type1", DbType="Int")]
		public System.Nullable<int> Type1
		{
			get
			{
				return this._Type1;
			}
			set
			{
				if ((this._Type1 != value))
				{
					this._Type1 = value;
				}
			}
		}
		
		[Column(Storage="_Type2", DbType="Int")]
		public System.Nullable<int> Type2
		{
			get
			{
				return this._Type2;
			}
			set
			{
				if ((this._Type2 != value))
				{
					this._Type2 = value;
				}
			}
		}
		
		[Column(Storage="_ProductId", DbType="Int NOT NULL")]
		public int ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				if ((this._ProductId != value))
				{
					this._ProductId = value;
				}
			}
		}
		
		[Column(Storage="_ProductType", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ProductType
		{
			get
			{
				return this._ProductType;
			}
			set
			{
				if ((this._ProductType != value))
				{
					this._ProductType = value;
				}
			}
		}
		
		[Column(Storage="_Price", DbType="Money")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[Column(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
	}
	
	public partial class search_SearchDiamondRing_个结果
	{
		
		private int _DiamondRingId;
		
		private string _StockNumber;
		
		private System.Nullable<int> _Type1;
		
		private int _ProductId;
		
		private string _ProductType;
		
		private System.Nullable<decimal> _Price;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		public search_SearchDiamondRing_个结果()
		{
		}
		
		[Column(Storage="_DiamondRingId", DbType="Int NOT NULL")]
		public int DiamondRingId
		{
			get
			{
				return this._DiamondRingId;
			}
			set
			{
				if ((this._DiamondRingId != value))
				{
					this._DiamondRingId = value;
				}
			}
		}
		
		[Column(Storage="_StockNumber", DbType="VarChar(20)")]
		public string StockNumber
		{
			get
			{
				return this._StockNumber;
			}
			set
			{
				if ((this._StockNumber != value))
				{
					this._StockNumber = value;
				}
			}
		}
		
		[Column(Storage="_Type1", DbType="Int")]
		public System.Nullable<int> Type1
		{
			get
			{
				return this._Type1;
			}
			set
			{
				if ((this._Type1 != value))
				{
					this._Type1 = value;
				}
			}
		}
		
		[Column(Storage="_ProductId", DbType="Int NOT NULL")]
		public int ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				if ((this._ProductId != value))
				{
					this._ProductId = value;
				}
			}
		}
		
		[Column(Storage="_ProductType", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ProductType
		{
			get
			{
				return this._ProductType;
			}
			set
			{
				if ((this._ProductType != value))
				{
					this._ProductType = value;
				}
			}
		}
		
		[Column(Storage="_Price", DbType="Money")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[Column(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
	}
	
	public partial class search_SearchGoldOrnament_个结果
	{
		
		private int _GoldOrnamentId;
		
		private string _OrnamentType;
		
		private System.Nullable<int> _Type1;
		
		private System.Nullable<int> _Type2;
		
		private int _ProductId;
		
		private string _ProductType;
		
		private System.Nullable<decimal> _Price;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		public search_SearchGoldOrnament_个结果()
		{
		}
		
		[Column(Storage="_GoldOrnamentId", DbType="Int NOT NULL")]
		public int GoldOrnamentId
		{
			get
			{
				return this._GoldOrnamentId;
			}
			set
			{
				if ((this._GoldOrnamentId != value))
				{
					this._GoldOrnamentId = value;
				}
			}
		}
		
		[Column(Storage="_OrnamentType", DbType="NChar(10)")]
		public string OrnamentType
		{
			get
			{
				return this._OrnamentType;
			}
			set
			{
				if ((this._OrnamentType != value))
				{
					this._OrnamentType = value;
				}
			}
		}
		
		[Column(Storage="_Type1", DbType="Int")]
		public System.Nullable<int> Type1
		{
			get
			{
				return this._Type1;
			}
			set
			{
				if ((this._Type1 != value))
				{
					this._Type1 = value;
				}
			}
		}
		
		[Column(Storage="_Type2", DbType="Int")]
		public System.Nullable<int> Type2
		{
			get
			{
				return this._Type2;
			}
			set
			{
				if ((this._Type2 != value))
				{
					this._Type2 = value;
				}
			}
		}
		
		[Column(Storage="_ProductId", DbType="Int NOT NULL")]
		public int ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				if ((this._ProductId != value))
				{
					this._ProductId = value;
				}
			}
		}
		
		[Column(Storage="_ProductType", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ProductType
		{
			get
			{
				return this._ProductType;
			}
			set
			{
				if ((this._ProductType != value))
				{
					this._ProductType = value;
				}
			}
		}
		
		[Column(Storage="_Price", DbType="Money")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[Column(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
