<?xml version="1.0" encoding="utf-8"?>
<Database Name="FuTai" Class="FuTaiDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=FuTai;Integrated Security=True" SettingsObjectName="FuTai.Component.Properties.Settings" SettingsPropertyName="FuTaiConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CardId" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="NickName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Authority" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Sex" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Impression" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Diamond" Member="Diamonds">
    <Type Name="Diamond">
      <Column Name="ProductID" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="StockNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Carat" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Clarity" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Cut" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DiamondGroup" Member="DiamondGroups">
    <Type Name="DiamondGroup">
      <Column Name="DiamondGroupId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiamondId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MetalType" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Style" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="RingBracketId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeleteDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DiamondOrnament" Member="DiamondOrnaments">
    <Type Name="DiamondOrnament">
      <Column Name="DiamondOrnamentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OrnamentType" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DiamondRing" Member="DiamondRings">
    <Type Name="DiamondRing">
      <Column Name="DiamondRingId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StockNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GoldOrnament" Member="GoldOrnaments">
    <Type Name="GoldOrnament">
      <Column Name="GoldOrnamentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OrnamentType" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Jewel" Member="Jewels">
    <Type Name="Jewel">
      <Column Name="JewelId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="JewelType" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PairRing" Member="PairRings">
    <Type Name="PairRing">
      <Column Name="PairRingId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StockNumber" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="RingType" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.RingBracket" Member="RingBrackets">
    <Type Name="RingBracket">
      <Column Name="BracketId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MetalType" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Style" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="StyleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Craft" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[&#x9;RingBracket]" Member="_RingBrackets">
    <Type Name="_RingBracket">
      <Column Name="RingBracketId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MetalType" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Style" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="StyleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Craft" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.search_SearchRingBracket" Method="SearchRingBracket">
    <Parameter Name="Price1" Parameter="price1" Type="System.Decimal" DbType="Decimal" />
    <Parameter Name="Price2" Parameter="price2" Type="System.Decimal" DbType="Decimal" />
    <Parameter Name="Type1" Parameter="type1" Type="System.Int32" DbType="Int" />
    <Parameter Name="Type2" Parameter="type2" Type="System.Int32" DbType="Int" />
    <ElementType Name="search_SearchRingBracket_个结果">
      <Column Name="BracketId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MetalType" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Style" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="StyleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Type1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Type2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Craft" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductType" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(0,0)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.search_SearchDiamond" Method="SearchDiamond">
    <Parameter Name="Price1" Parameter="price1" Type="System.Decimal" DbType="Decimal" />
    <Parameter Name="Price2" Parameter="price2" Type="System.Decimal" DbType="Decimal" />
    <Parameter Name="Type1" Parameter="type1" Type="System.Int32" DbType="Int" />
    <Parameter Name="Type2" Parameter="type2" Type="System.Int32" DbType="Int" />
    <ElementType Name="search_SearchDiamond_个结果">
      <Column Name="DiamondID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StockNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Carat" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Clarity" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Cut" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductType" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.search_SearchDiamondOrnament" Method="SearchDiamondOrnament">
    <Parameter Name="Price1" Parameter="price1" Type="System.Decimal" DbType="Decimal" />
    <Parameter Name="Price2" Parameter="price2" Type="System.Decimal" DbType="Decimal" />
    <Parameter Name="Type1" Parameter="type1" Type="System.Int32" DbType="Int" />
    <Parameter Name="Type2" Parameter="type2" Type="System.Int32" DbType="Int" />
    <ElementType Name="search_SearchDiamondOrnament_个结果">
      <Column Name="DiamondOrnamentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OrnamentType" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Type1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Type2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductType" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.search_SearchJewel" Method="SearchJewel">
    <Parameter Name="Price1" Parameter="price1" Type="System.Decimal" DbType="Decimal" />
    <Parameter Name="Price2" Parameter="price2" Type="System.Decimal" DbType="Decimal" />
    <Parameter Name="Type1" Parameter="type1" Type="System.Int32" DbType="Int" />
    <Parameter Name="Type2" Parameter="type2" Type="System.Int32" DbType="Int" />
    <ElementType Name="search_SearchJewel_个结果">
      <Column Name="PairRingId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StockNumber" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="RingType" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Type1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductType" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.search_SearchPairRing" Method="SearchPairRing">
    <Parameter Name="Price1" Parameter="price1" Type="System.Decimal" DbType="Decimal" />
    <Parameter Name="Price2" Parameter="price2" Type="System.Decimal" DbType="Decimal" />
    <Parameter Name="Type1" Parameter="type1" Type="System.Int32" DbType="Int" />
    <Parameter Name="Type2" Parameter="type2" Type="System.Int32" DbType="Int" />
    <ElementType Name="search_SearchPairRing_个结果">
      <Column Name="GoldOrnamentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OrnamentType" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Type1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Type2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductType" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.search_SearchDiamondRing" Method="SearchDiamondRing">
    <Parameter Name="Price1" Parameter="price1" Type="System.Decimal" DbType="Decimal" />
    <Parameter Name="Price2" Parameter="price2" Type="System.Decimal" DbType="Decimal" />
    <Parameter Name="Type1" Parameter="type1" Type="System.Int32" DbType="Int" />
    <Parameter Name="Type2" Parameter="type2" Type="System.Int32" DbType="Int" />
    <ElementType Name="search_SearchDiamondRing_个结果">
      <Column Name="DiamondRingId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StockNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Type1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductType" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.search_SearchGoldOrnament" Method="SearchGoldOrnament">
    <Parameter Name="Price1" Parameter="price1" Type="System.Decimal" DbType="Decimal" />
    <Parameter Name="Price2" Parameter="price2" Type="System.Decimal" DbType="Decimal" />
    <Parameter Name="Type1" Parameter="type1" Type="System.Int32" DbType="Int" />
    <Parameter Name="Type2" Parameter="type2" Type="System.Int32" DbType="Int" />
    <ElementType Name="search_SearchGoldOrnament_个结果">
      <Column Name="GoldOrnamentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OrnamentType" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Type1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Type2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductType" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>